#Program 1: Lottery
#Create a program that ask 3 numbers (0-9) from the user.
#Generate 3 random winning numbers (0-9)
#Display “Winner” if all 3 input numbers matched the generated numbers
#Display ”You loss” if not
#Display ”Try again y/n” after each game
#If the user enter “y” the user will play again
#if “n” the program will exit.

# Added import function
from random import randint
import os, sys
os.system('cls')




# Added greetings, input function for the name
print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
print("                                                    \033[93m\033[1m Welcome to LOTTOHAN NI CARLITO!\033[93m\033[0m ")
print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
name = input('Please state your \033[4mname\033[0m: ')
print(f'\033[95m\033[1mHi, \033[4m{name}\033[0m\033[95m!\033[95m\033[0m\033[0m \033[95m\033[1mPlease follow the given instructions carefully!\033[0m\033[0m')
print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')

# Instructions for the user.
print('                                                             \033[94mDIRECTIONS:\033[0m ') 
print('                           \033[94mYou only have to do is to guess the three numbers that will be generated by the program.\033[0m')
print('                                     \033[94mIf your answers matched the random three numbers, you WIN!\033[0m')
print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')

# Added a def function together with the input function to make the user guess the number given by random generator.
def Lotterygame():

    lotto_num = 0
    lottery = []
    numbers_userinput = []
    correct_guess = 0
    
    while len(lottery) < 3 and len(numbers_userinput) < 3 :
        lotto_num = randint(0,9)
        if (lotto_num not in lottery):
            lottery.append(lotto_num)
        lotto_num = int(input("\033[96mPlease Enter a number between 0-9:\033[0m "))
        if (lotto_num not in numbers_userinput and (lotto_num <= 9 or lotto_num >= 0)):
            numbers_userinput.append(lotto_num)
# Added a formula for computing the right guess of the user.
    for number in lottery:
        for input_number in numbers_userinput:
            if (number == input_number):
                correct_guess +=1        

    
# Adding display so that the user will know if he/she wins.
    print ('\n\033[100mYou got ' + str(correct_guess) + ' right number(s)!\033[0m')
    print(f'\n\033[95mThe lottery results are: \n{lottery}\033[95m')
# The correct guess determines if the user wins or not
    if correct_guess == 0:
        print('\033[91mYou lose!\033[0m')
        print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
    elif correct_guess == 1:
        print('\033[91mYou lose!\033[0m')
        print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
    elif correct_guess == 2:
        print('\033[91mYou lose!\033[0m')
        print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
    else:
        print('\033[91mYou win!\033[0m')
        print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')

    
# Asks the user if he/she still wants to play or not.
    Answer = str(input('\033[37mDo you still want to play? \nYes or No?:\033[0m \n>> '))
    print('\033[1m\033[92m---------------------------------------------------------------------------------------------------------------------------------------\033[0m\033[0m')
    if Answer == 'Yes'or Answer == 'yes' or Answer == 'Y' or Answer == 'y':
        return Lotterygame()
    elif Answer == 'No' or Answer == 'no' or Answer == 'N' or Answer == 'n':
        print('Thank you for playing! Have a nice day!')
        sys.exit

Lotterygame()