#Program 1: Lottery
#Create a program that ask 3 numbers (0-9) from the user.
#Generate 3 random winning numbers (0-9)
#Display “Winner” if all 3 input numbers matched the generated numbers
#Display ”You loss” if not
#Display ”Try again y/n” after each game
#If the user enter “y” the user will play again
#if “n” the program will exit.

# Added import function
from random import randint
import os, sys
os.system('cls')




# Added greetings, input function for the name
print('---------------------------------------------------------------------------------------------------------------------------------------')
print("                                       Welcome to LOTTOHAN NI CARLITO! ")
name = input('Please state your name: ')
print(f'Hi, {name}! Please follow the given instructions carefully!')
print('---------------------------------------------------------------------------------------------------------------------------------------')

# Instructions for the user.
print('DIRECTIONS: \nYou only have to do is to guess the three numbers that will be generated by the program.') 
print('If your answers matched the random three numbers, you WIN!')
print('---------------------------------------------------------------------------------------------------------------------------------------')

# Added a def function together with the input function to make the user guess the number given by random generator.
def Lotterygame():

    lotto_num = 0
    lottery = []
    numbers_userinput = []
    correct_guess = 0
    
    while len(lottery) < 3 and len(numbers_userinput) < 3 :
        lotto_num = randint(0,9)
        if (lotto_num not in lottery):
            lottery.append(lotto_num)
        lotto_num = int(input("Please Enter a number between 0-9: "))
        if (lotto_num not in numbers_userinput and (lotto_num <= 9 or lotto_num >= 0)):
            numbers_userinput.append(lotto_num)
# Added a formula for computing the right guess of the user.
    for number in lottery:
        for input_number in numbers_userinput:
            if (number == input_number):
                correct_guess +=1        

    
# Adding display so that the user will know if he/she wins.
    print ('\nYou got ' + str(correct_guess) + ' right number(s)!')
    print(f'\nThe lottery results are: \n{lottery}')
# The correct guess determines if the user wins or not
    if correct_guess == 0:
        print('You lose!')
        print('---------------------------------------------------------------------------------------------------------------------------------------')
    elif correct_guess == 1:
        print('You lose!')
        print('---------------------------------------------------------------------------------------------------------------------------------------')
    elif correct_guess == 2:
        print('You lose!')
    else:
        print('You win!')
    
# Asks the user if he/she still wants to play or not.
    Answer = str(input('Do you still want to play? \nYes or No?: \n>> '))
    print('---------------------------------------------------------------------------------------------------------------------------------------')
    if Answer == 'Yes'or Answer == 'yes' or Answer == 'Y' or Answer == 'y':
        return Lotterygame()
    elif Answer == 'No' or Answer == 'no' or Answer == 'N' or Answer == 'n':
        print('Thank you for playing! Have a nice day!')
        sys.exit

Lotterygame()